### ISSUE TITLE
Need unMinify JS 

### ISSUE THREAD

**Issue by agsachdev** [Log1x/acf-phone-number#1]
I need Some Modification please add unMinify Version of JS

**Comment by Log1x** [comment]
https://github.com/Log1x/acf-phone-number/blob/master/assets/js/field.js

**Comment by agsachdev** [comment]
No, need a full unMinify file of  https://github.com/Log1x/acf-phone-number/blob/master/dist/js/field.js

**Comment by Log1x** [comment]
That is the full unminified file. It is just importing https://github.com/jackocnr/intl-tel-input

**Comment by Log1x** [comment]
You can build it locally by pulling the repo down and doing `yarn && yarn build`
