### ISSUE TITLE
Multiple phone numbers on one page results in only the last number being output

### ISSUE THREAD

**Issue by JacobDB** [Log1x/acf-phone-number#10]
With multiple phone numbers set, it seems that only the last phone number can be output. In the example below, assuming "+13128675309" is set to `$phone_number` and "+13128675310" is set to `$fax_number`, both `echo`s will output "+13128675310".

```php
$phone_number = get_field("phone_number", "theme");
$fax_number   = get_field("fax_number", "theme");

echo $phone_number->national;
echo $fax_number->national;
```

This has only been tested when installed without composer, per #8.

Am I doing this incorrectly, or is this a bug?

**Comment by JacobDB** [comment]
Nevermind! If I convert the value to an array before calling in the second field, it works. Thanks!

**Comment by JacobDB** [comment]
Just spent a few minutes trying to get this to work automatically with `acf/format_value/type=phone_number`, but that doesn't seem to be possible. I think it'd be awesome if something like that could work (even if it's a hook as part of this plugin), but my solution does work, so it's fine, just not super elegant.

**Comment by Log1x** [comment]
I'll think about a better approach to fix these problems.

**Comment by JacobDB** [comment]
@Log1x running in to this issue again, in a `foreach`... is there a way to fix this? I'm basically doing this:

```php
$phone_numbers = get_field("phone_numbers", "options");

foreach ($phone_numbers as $data) {
    $phone_number = $data["phone_number"]->toArray();

    echo "<pre>";
    print_r($phone_number);
    echo "</pre>";
}
```

This is resulting in every every loop outputting the last value in the array... doesn't make a ton of sense to me.

**Comment by JacobDB** [comment]
Looking through the code, I think the problem is that it's implemented as a "singleton," which to my understanding only one instance can exist on a page at once.

**Comment by JacobDB** [comment]
Made some progress, but I'm not a fan of this solution.

```php
$phone_numbers = get_field("phone_numbers", "theme");
$phone_numbers_fixed = [];

foreach ($phone_numbers as $key => $data) {
    if ($raw = get_option("theme_phone_numbers_{$key}_phone_number")) {
        $parsed = new PhoneNumber($raw);
        $phone_numbers_fixed[] = $parsed->toArray();
    } else {
        $phone_numbers_fixed[] = null;
    }
}

foreach ($phone_numbers_fixed as $data) {
    echo $data["phone_number"]->e164;
}
```

By accessing the values outside of ACF, I can get each instance individually and convert it, rather than each instance being generated in the repeater and stored in an array (which results in only the last instance being accessible). The drawback is that this retrieves the same value from the database twice for each number, and the code is... sloppy. I feel like there's got to be a better solution, maybe if I tie in to the `acf/fiels/type=repeater` hook I can do this there, but I doubt it... will have to keep looking.

**Comment by Log1x** [comment]
are you on the latest version? I didn't think this should be an issue anymore since #17

**Comment by JacobDB** [comment]
Yep, you were right 🤦‍♂️ Thanks, I should've checked that a lot sooner, my bad. It's been a long week 😅
