### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by MGParisi** [Log1x/acf-phone-number#11]
Parse error: syntax error, unexpected 'class' (T_CLASS) in /home4/cresceu1/public_html/staging/wp-content/plugins/acf-phone-number-master/plugin.php on line 14

**Comment by MGParisi** [comment]
I'm assuming this has to do with PHP version.

**Comment by Log1x** [comment]
yeah. i think PHP7 would be the bare minimum in it's current state
