### ISSUE TITLE
Data does not register/save after being submitted.

### ISSUE THREAD

**Issue by Bpaul1416** [Log1x/acf-phone-number#15]
Data does not register after being submitted.
So when a user inputs a phone number it does not save into my database. 

Furthermore, once exported this field has the error code "O:32:"Log1x\AcfPhoneNumber\PhoneNumber":2:{s:11:""

**Comment by Log1x** [comment]
That doesn't look like the error code, that's the PhoneNumber instance.

Try calling `var_dump(get_field('your_number')->toArray())`
