### ISSUE TITLE
Phone number field within repeater always returns the same PhoneNumber object

### ISSUE THREAD

**Issue by emanueljacob** [Log1x/acf-phone-number#16]
Hi,

first: thanks for this and all the other great packages!

I have a problem with this one. When creating more than one tel field (i.e. 'tel', 'mobile') within a repeater field, it looks like everything works fine, meaning:
- wp admin fields are saving correctly
- wp admin fields are visually correct
- database post_content data (acf block) seems fine (i.e. <br>
```
       "rows_0_person_tel": {
            "number": "+49 1212312",
            "country": "de"
        },
        "_rows_0_person_tel": "field_introduction_rows_person_tel",
        "rows_0_person_mobile": {
            "number": "+49 12121",
            "country": "de"
        },
        "_rows_0_person_mobile": "field_introduction_rows_person_mobile",
        "rows_0_person_fax": {
            "number": "+49 121231231",
            "country": "de"
        },

...
```
<br>-->see following example, for more information)
- however, when getting the fields values in the frontend, it __always gets the same PhoneNumber object, meaning that the phone number is always the first I got__...

My setup:
- roots/bedrock
- roots/sage (version 10)
- samrap/acf-fluent
- log1x/acf-composer
- log1x/acf-phone-number (as mu-plugin)
- acf-pro (4.9.4)

### Full example

I created a custom block (actually a lot of blocks), using acf-composer, this one (simplified) in the following example:

#### Block class (relevant part only)

```php
class Introduction extends Block {
//...
    public function with(){
        return ['rows' => $this->rows(),];
    }
//...
	public function fields() {
		$block = new FieldsBuilder('introduction');

	    $block
	        ->addAccordion($this->slug . 'accordion', ['label' => $this->name,])
	            ->addMessage($this->name, $this->description, ['label' => ''])
	            ->addTab('content', ['label' => __('Content', 'sage')])
	                //...
	                ->addRepeater('rows', ['label' => __('Rows', 'sage'), 'button_label' => __('Add row')])
	                   //... 
	                    ->addGroup('person', ['label' => __('Person', 'sage'), 'wrapper' => ['width' => self::$width['3-4']]]
	                        ->addField('tel', 'phone_number', ['default_country' =>'de', 'label' => __('Tel', 'sage')])
	                        ->addField('mobile', 'phone_number', ['default_country' =>'de', 'label' => __('Mobil', 'sage')])
						//...
						->endGroup()
					->endRepeater();
		//...
		return $block->build();
	}
// ...

    public function rows(){
        // also tested: get_field('rows);
        return field('rows')->expect('array')->default([])->get(); // acf-fluent
    }
```

I loop over the rows array in my block view afterwards. Something like this:

`introduction.blade.php`
```php
@php
    // for illustration only. Simple closure to get the international value of the phonenumber (is there an easier way?)
    $telNum = function($field) {
        return $field instanceof \Log1x\AcfPhoneNumber\PhoneNumber ? $field->international() : '';
     };
@endphp
@if($rows)
        <div>
              @foreach($rows as $row)
                  @if($person = $row['person'])
                      <div>{!! $telNum($person['tel'] ?? null) !!}</div>
                      <div>{!! $telNum($person['mobile'] ?? null) !!}</div>
                  @endif
               @endforeach
        </div>
@endif

```

expected result (fictive numbers):
`+491 12345`
`+491 65646`

actual result:
`+491 12345`
`+491 12345`

when dumping `$rows` i see that for each `$row` item in `$rows`, the object stored in `$row['person_tel]` equals the  object stored in `$row['person_mobile]`. 

### Additional notes
As I have already written in a short comment, I also tested the acf default function `get_field` but this didn't seem to change anything.

Any idea about the how and why? Actually im not quite sure, whether I am doing it wrong, acf pro gets the values wrong or its the responsibility of your plugin.

**Comment by Log1x** [comment]
you need to return each instance using `$field->toArray()`

**Comment by emanueljacob** [comment]
@Log1x I'm sorry I didn't understand that, would you mind given me a bit more infos in context to the given example?
Where would you do that in my code?



If I died in the field method I would get wrong results, how could an `toArray()` change that?
```php
public function rows(){
    dd(field('rows')->expect('array')->default([])->get()); // acf-fluent
}
```

result (something like this) - note the instance ids (8120).
```php

array:1 [
    0 => [
        "image" => false, 
        "person" => array:10 [
	     "tel" => Log1x\AcfPhoneNumber\PhoneNumber {#8120 ▶} ,
	     "mobile" => Log1x\AcfPhoneNumber\PhoneNumber{#8120 ▶}, 
	     "fax" => Log1x\AcfPhoneNumber\PhoneNumber {#8120 ▶} ,
        ]
    ]
],
```


even if i got the field itself within separated methods to be used in the with method, i would get wrong results:
```php
    public function with()
    {
        return array_merge( parent::with(), [
            'telDemo' => $this->telDemo(),
            'faxDemo' => $this->faxDemo(),
        ]);
    }

    public function telDemo()
    {
        return field('rows_0_person_tel')->get();
    }

    public function faxDemo()
    {
        return field('rows_0_person_fax')->get();
    }

```

results:
```php

^ Log1x\AcfPhoneNumber\PhoneNumber {#8120 ▼
  #instance: libphonenumber\PhoneNumberUtil {#8123 ▶}
  #number: libphonenumber\PhoneNumber {#9479 ▶}
}
^ Log1x\AcfPhoneNumber\PhoneNumber {#8120 ▼
  #instance: libphonenumber\PhoneNumberUtil {#8123 ▶}
  #number: libphonenumber\PhoneNumber {#9479 ▶}
}
```

indeed, I would get different results if i fetched the value of the object for each item one by one:

```php
    public function with()
    {
        return array_merge( parent::with(), [
            'telDemo' => $this->telDemo(),
            'faxDemo' => $this->faxDemo(),
        ]);
    }

    public function telDemo()
    {
        return field('rows_0_person_tel')->get()->international();
    }

    public function faxDemo()
    {
        return field('rows_0_person_fax')->get()->international();
    }

```

results (correct):
```php
^ "+49 1212312"
^ "+49 121231231"
```


but wouldn't that mean, that I had to know the index before passing the data to the view?
It wouldn't even work to map each item of the repeater field (rows) in order to convert the PhoneNumber object to the string using international(), because at the moment the $row array has been created each containing element of type PhoneNumber has already overridden itself? 
In the following example i create a collection of the repeater field ($rows), and map all items until the sub sub items and in case the item is of type `PhoneNumber` i convert it to become the international string (that i want in the end)) -  Example (__not very clean but you get an idea__):

```php
public function rows()
    {
        dd(collect(field('rows')->expect('array')->default([])->get())
            ->map(function($item){
                return collect($item)->map(function($subItem){
                    return collect($subItem)->map(function($subsubItem){
                        if($subsubItem instanceof \Log1x\AcfPhoneNumber\PhoneNumber){
                            return $subsubItem->international();
                        }
                        return $subsubItem;
                    })->all();
                })->all();
            })->all()
        );
    }
```

result (incorrect: all tel, fax, mobile numbers are the same):
```php
^ array:1 [
  0 => array:2 [
  	"image" => array:1[
  		//...
  	],
	"person" => array:10 [
		"tel" => "+49 121231231",
		"mobile" => "+49 121231231",
		"fax" => "+49 121231231",
		"mail" => "asds@ded.de",
	 ]
]
```

**Comment by Log1x** [comment]
something like

```php
public function rows()
{
    return collect(
        field('rows')->expect('array')->default([])->get()
    )->map(function($item) {
        if (! empty($item['person'])) {
            foreach ($item['person'] as $key => $value) {
                $item['person'][$key] = Arr::get($value->toArray(), 'international', $value);
            }
        }

        return $item;
    })->all();
}
```

**Comment by Log1x** [comment]
ill fix the need to do this today

**Comment by Log1x** [comment]
`composer require log1x/acf-phone-number:dev-fix/16`

any chance you could try this out?

**Comment by emanueljacob** [comment]
Thank you @Log1x it works right out of the box. Also thank your for your fast replies and your example

**Comment by Log1x** [comment]
no problem. published the new version 🎉
