### ISSUE TITLE
Exception and inconsistent return values when calling methods on PhoneNumber instances with no number property value

### ISSUE THREAD

**Issue by emanueljacob** [Log1x/acf-phone-number#18]
when calling methods like `$field->international()` while $field is an instance of `PhoneNumber` (but the number property is empty) an exception will be thrown whenever the value has not been set yet. 

This behavior is kind of inconsistent and unexpected (see examples below).
Almost every method like `international` will **not**  check for a _valid_ (not simply empty) `number` property but the `toArray` method does that. 

consider following use cases:
CASe A) $field is not set:
- $field is instance of `PhoneNumber`
- $field->international() - will throw an exception // because there is no check for an empty number
- $field->toArray() - will return an empty array // because there is check of an empty value (in `isValid()`)

example (value not set, exception when calling `$field->international()`:
```php
Argument 1 passed to libphonenumber\PhoneNumberUtil::format() must be an instance of libphonenumber\PhoneNumber, null given, called in /app/web/web/app/mu-plugins/acf-phone-number/src/PhoneNumber.php on line 130 (View:
``` 

CASE B) $field has been set with an:
- $field is instance of `PhoneNumber`
- $field->international() - will return the number // this time the number is set (but not `valid`), so we can access it
- $field->toArray() - will return an empty array // because there is not just the check of an empty value __ but also  a check for valid number in `isValid()`)

example (first with `toArray()`, second with `international()`)
<img width="1098" alt="screenshot" src="https://user-images.githubusercontent.com/28386816/109333117-52203200-785f-11eb-8669-e9d507cefd06.png">

So i would suggest to check the number in all corresponding phone number methods (i.e. `international`) or similar or at least add a method to check whether the property is empty or not. 

What do you think?

**Comment by Log1x** [comment]
definitely an oversight.

care to do a PR adding

```
if (! $this->isValid()) {
    return;
}
```

on those?

**Comment by emanueljacob** [comment]
done ;)
