### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by julientora** [Log1x/acf-phone-number#20]
Hello,

I am currently working on a Wordpress 5.7 site with PHP 8.0. The plugin returns a 500 error when activated. The same on PHP 7.4. Everything is ok when deactivated. 
![Capture d’écran 2021-04-13 à 14 28 03](https://user-images.githubusercontent.com/38557341/114552102-82336100-9c64-11eb-903c-3c0a827fce39.jpg)

Thank you for maintaining this very useful plugin !

**Comment by Log1x** [comment]
Does your environment have php-intl?

**Comment by julientora** [comment]
Hello, 

No.

**Comment by Log1x** [comment]
It's listed as a requirement and you'll need it to use the plugin due to its dependency on libphonenumber.

https://www.php.net/manual/en/intl.installation.php

**Comment by julientora** [comment]
Ok ! So sorry, I hadn't seen it...
