### ISSUE TITLE
Location, settings and field group meta boxes hidden

### ISSUE THREAD

**Issue by thuijssoon** [Log1x/acf-phone-number#24]
Hi there,

Great plugin!

When I add a phone number field and update the field group the location, settings and field group meta boxes are gone... The is most likely due to a javascript error as other javascript features are not working either. I have checked the console but nothing suspicious is showing.

I am using:
WP version 5.7.2
ACF Pro version 5.9.6
acf-phone-number version 1.1.4 (manual install)

I hope this is enough info to help resolve this issue. Please let me know if you require additional information.

**Comment by Log1x** [comment]
is there anything in your nginx/apache error log?

**Comment by Log1x** [comment]
probably related to #23
