### ISSUE TITLE
Manual install with Sage 9 error

### ISSUE THREAD

**Issue by djmtype** [Log1x/acf-phone-number#28]
I'm trying to install this manually, but get this error: 

```
Fatal error: Uncaught Error: Class 'Log1x\AcfPhoneNumber\PhoneNumberField' not found in /Volumes/Evo/Local/gateway/app/public/wp-content/plugins/acf-phone-number/plugin.php on line 50
```

**Comment by Log1x** [comment]
Are you using the "release" download? https://github.com/Log1x/acf-phone-number/releases/download/v1.1.6/acf-phone-number-v1.1.6.zip

**Comment by djmtype** [comment]
Thanks @Log1x That did it but a new issue came up.
