### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by paulo-carvajal** [Log1x/acf-phone-number#32]
I get this error on activation in a clean installation with only ACF and ac-phone-number (ziped donwload) plugins installed:

WP 5.8.1, PHP 7.4.1, Apache 2.4.43, MySQL 8.0.16

PHP Fatal error:  Uncaught Error: Class 'Log1x\AcfPhoneNumber\PhoneNumberField' not found in /Users/user/Local/wp/app/public/wp-content/plugins/acf-phone-number-master/plugin.php:50
Stack trace:
#0 /Users/user/Local/wp/app/public/wp-includes/class-wp-hook.php(303): class@anonymous->Log1x\AcfPhoneNumber\{closure}(5)
#1 /Users/user/Local/wp/app/public/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#2 /Users/user/Local/wp/app/public/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /Users/user/Local/wp/app/public/wp-content/plugins/advanced-custom-fields-pro/acf.php(273): do_action('acf/include_fie...', 5)
#4 /Users/user/Local/wp/app/public/wp-includes/class-wp-hook.php(303): ACF->init('')
#5 /Users/user/Local/wp/app/public/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#6 /Users/user/Local/wp/app/public/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#7 /Users/user/Local/wp/app/public/wp-settings.php(578): do_action('init')
#8 /Users/user/Local/wp/app/public/wp-content/plugins/acf-phone-number-master/plugin.php on line 50

**Comment by paulo-carvajal** [comment]
Solved, it was a permissions issue. Sorry to bother.

**Comment by poonasor** [comment]
> Solved, it was a permissions issue. Sorry to bother.

sorry how did you resolve this? which permissions did you change?

**Comment by Log1x** [comment]
Make sure you're downloading the latest release, not the source code.

https://github.com/Log1x/acf-phone-number/releases/download/v1.1.6/acf-phone-number-v1.1.6.zip
