### ISSUE TITLE
ACF "required" validation is not working

### ISSUE THREAD

**Issue by tzahif1** [Log1x/acf-phone-number#35]
When marking a field based on acf-phone as required, its not actually catch if no value entered and the form is passing successfully (although no value saved in the user meta table).
I am suspecting that its due to the fact that the default country code is always filled.

**Comment by Log1x** [comment]
Are you trying to use the required validation in blocks or a field group?

https://github.com/Log1x/acf-phone-number/blob/master/src/PhoneNumberField.php#L156= the validation code is pretty straight forward, I'm not sure why it wouldn't be catching it. Any chance you could debug there?

**Comment by timoteh** [comment]
Same problem here. 

@Log1x , i believe it's because `$valid` is returned  in the first `if`, if you dump it, the value is `true`, even though we have an empty number:

`if (! is_array($value) || empty($value['number'])) {
      return $valid;
}`

**Comment by Log1x** [comment]
Could you try changing it to `return false;` and see if everything works as expected? If so a PR would be great.

**Comment by timoteh** [comment]
Tested on my project and it works fine. 
Made a pull request here:

#47
