### ISSUE TITLE
Phone Number cannot be left empty

### ISSUE THREAD

**Issue by WeFabric-Kevin** [Log1x/acf-phone-number#49]
Hi, we're using your plugin to structure and display information about company locations. The phone number field is not required to be filled in, but when I try to save the page without filling in a phone number, I get an error saying _"The phone number cannot be empty."_.

I believe the issue stems from here: https://github.com/Log1x/acf-phone-number/blob/master/src/PhoneNumberField.php#L156

Is there any way you can check for the ACF option for setting a field as required?
Thank you!

**Comment by Log1x** [comment]
Hi.

Sorry I should've tested this more. Will look into it ASAP.

For now use v1.1.6 https://github.com/Log1x/acf-phone-number/releases/tag/v1.1.6

**Comment by Log1x** [comment]
This should be fixed in v1.1.9.

Let me know if you have any issues.

**Comment by WeFabric-Kevin** [comment]
Hi, thanks for your quick reply! It seems to be working correctly now!
