### ISSUE TITLE
Class not found - need any help?

### ISSUE THREAD

**Issue by mrtnm** [Log1x/acf-phone-number#53]
Hi there,

I think this is a plugin everybody wants and needs (maybe Elliot Condon just wants to integrate it, also it seems to be part of ACF Extended), but unfortunately the current version has some errors:

On activating the plugin, it dies with:
Error: Class 'Log1x\AcfPhoneNumber\PhoneNumberField' not found in /var/[...]/wp-content/plugins/acf-phone-number-master/plugin.php:53

I am on WordPress 6.0.3 (Multisite), ACF Pro 6.0.3.

If I can be of any need help, drop me a line.

Cheers,
Marten

**Comment by Log1x** [comment]
Make sure you are downloading the release zip and not the source code.

https://github.com/Log1x/acf-phone-number/releases/download/v1.2.0/acf-phone-number-v1.2.0.zip

**Comment by mrtnm** [comment]
Ah.
Hero.
My bad, sorry.
