### ISSUE TITLE
Fatal Error upon activation

### ISSUE THREAD

**Issue by dbrabyn** [Log1x/acf-phone-number#56]
> [01-Nov-2022 15:11:37 UTC] PHP Fatal error:  Uncaught Error: Class "Log1x\AcfPhoneNumber\PhoneNumberField" not found in .../app/public/wp-content/plugins/acf-phone-number-master/plugin.php:50
Stack trace:
#0 .../app/public/wp-includes/class-wp-hook.php(307): class@anonymous->Log1x\AcfPhoneNumber\{closure}(5)
#1 .../app/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 .../app/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 .../app/public/wp-content/plugins/advanced-custom-fields-pro/acf.php(297): do_action('acf/include_fie...', 5)
#4 .../app/public/wp-includes/class-wp-hook.php(307): ACF->init('')
#5 .../app/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#6 .../app/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#7 .../app/public/wp-settings.php(598): do_action('init')
#8 .../app/public/wp-config.php(92): require_once('/Users/davidbra...')
#9 .../app/public/wp-load.php(50): require_once('/Users/davidbra...')
#10 .../app/public/wp-admin/admin-ajax.php(22): require_once('/Users/davidbra...')
#11 {main}
  thrown in .../app/public/wp-content/plugins/acf-phone-number-master/plugin.php on line 50

Installed manually

**Comment by Log1x** [comment]
https://github.com/Log1x/acf-phone-number/releases/download/v1.2.0/acf-phone-number-v1.2.0.zip please use the release zip, not the source code.
