### ISSUE TITLE
validation not working Advanced Form 

### ISSUE THREAD

**Issue by agsachdev** [Log1x/acf-phone-number#6]
![image](https://user-images.githubusercontent.com/24837693/97079498-0ab83980-1612-11eb-901c-5fd72b1006f2.png)

**Comment by agsachdev** [comment]
I am waiting for an answer!

**Comment by Log1x** [comment]
I'm not 100% sure as I don't use Advanced Forms.

https://github.com/Log1x/acf-phone-number/blob/master/src/PhoneNumberField.php#L159-L180 could you perhaps try tweaking this and seeing if you can spot where it is failing to verify?

**Comment by Log1x** [comment]
Any luck with this?
