### ISSUE TITLE
REST API - is not accepting phone number

### ISSUE THREAD

**Issue by swapnali-kdc** [Log1x/acf-phone-number#69]
#REST API - is not accepting phone number

**Issue Description**

1) We tried passing e.164 formatted number.
```
{
"acf": {
"user_mobile": "+910000000000"
}
}
```

2) Also tried the formatted array.
```
{
"acf": {
"user_mobile": {
"carrier": "XYZ",
"country": "India",
"e164": "+91000000000",
"international": "+91 00000 00000",
"location": "India",
"national": "000000 00000",
"number": "000000 00000",
"rfc3966": "tel:+91-00000-00000",
"timezone": [
"Asia/Calcutta"
],
"uri": "tel:+910000000000"
}
}
}
```

3) Event tried db entry format:
```
{
"acf": {
"user_mobile": {
"number": "+91 00 0000 0000",
"country": "in"
}
}
}

===
ERROR for 1:::
It simply overrides to an empty value.
```
{
acf": {
"user_mobile": []
}
}
```

ERROR for 2 & 3:::
```
{
"code": "rest_invalid_param",
"message": "Invalid parameter(s): acf",
"data": {
"status": 400,
"params": {
"acf": "acf[user_mobile] is not of type string,null."
},
"details": {
"acf": {
"code": "rest_invalid_type",
"message": "acf[user_mobile] is not of type string,null.",
"data": {
"param": "acf[user_mobile]"
}
}
}
}
}
```

**THIS IS A REST API ISSUE.**
---
When we pass the REST API value as such...

```
curl --location 'https://wp.host/wp-json/wp/v2/users/4' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==' \
--data '{
    "acf": {
        "user_mobile": {"number":"+91 00 0000 0000","country":"in"}
    }
}'

```

That is the URL from Postman where is --data is the 3) version of the input. But inputs are giving issues. 

https://capture.dropbox.com/eDrI1M3KE8BYCOXv


All other ACF fields are saving and working without error.
Only when the field type is "ACF Phone Number" those are the ones that are giving and error or saving empty.

**Comment by joostdekeijzer** [comment]
The REST schema is not correctly set, see PR for a fix.

In the meantime you can use
```
add_filter( 'acf/rest/get_field_schema/type=phone_number', function ( $schema ) {
    $schema['type'] = array( 'object', 'null' );
    $schema['properties'] = array(
        'country' => array(
            'type' => 'string',
        ),
        'number' => array(
            'type' => array( 'string', 'int' ),
        ),
    );

    return $schema;
}, 10, 1 );
```
