### ISSUE TITLE
Can't get correct phone field data when using with repeater fields

### ISSUE THREAD

**Issue by smeedijzer-internet** [Log1x/acf-phone-number#7]
Hi,

The phone object doesn't seem to work when using the ACF Phone Field within repeater fields. I looked at issue: [https://github.com/Log1x/acf-phone-number/issues/3](url), but can't get it working. It shows the first number of the repeater field on all the rows. This is what I tried:

```
if( have_rows('locations', $post->ID) ):
    while( have_rows('locations', $post->ID) ) : the_row();
        if( have_rows('casemanagers', $post->ID) ):
            while( have_rows('casemanagers', $post->ID) ) : $row = the_row(); // the_row(true)
                $phone = get_sub_field('phone'); // get_sub_field('phone', $row); // get_sub_field('phone', $post->ID);
                var_dump( $phone->toArray());
                var_dump( $phone->national);
            endwhile;
        endif;
    endwhile;
endif;
```

I hope you can help my solve this :)

**Comment by Log1x** [comment]
I'll have to test this when I get a moment. In any case, it'd be necessary for you to use `->toArray()`

**Comment by Log1x** [comment]
Did you happen to tinker and figure out why this was happening?

**Comment by smeedijzer-internet** [comment]
I forgot to come back at this issue. I'm not sure what I did wrong, somehow it suddenly worked. This is what I ended up with:

```
...
$casemanagers = [];

if (have_rows('casemanagers', $post->ID)) :
    while (have_rows('casemanagers', $post->ID)) : the_row();
        $casemanagers[] = (object) [
            'name' => get_sub_field('name'),
            'phone' => (object) get_sub_field('phone')->toArray(),
        ];
    endwhile;
endif;
...
```

I think the issue can be closed.

**Comment by Log1x** [comment]
nice! appreciate the reply.
