### ISSUE TITLE
Preset placeholder text

### ISSUE THREAD

**Issue by chriscapisce** [Log1x/acf-phone-number#75]
Hi, thanks for this great plugin. It would be awesome to be able to preset the placeholder text since I'm also using landline telephone numbers apart from mobile phone numbers. Thanks in advance!

**Comment by chriscapisce** [comment]
For anyone interested: I did it through a function and loading a javascript file in the backend.

**function**
`function load_acf_phonenumber_placeholder() {
    wp_enqueue_script( 'acf_phonenumber_placeholder', get_stylesheet_directory_uri() . '/js/acf-phonenumber-overwrite-placeholder.js', array(), '1.0', true );
}
add_action( 'admin_enqueue_scripts', 'load_acf_phonenumber_placeholder' );`

**acf-phonenumber-overwrite-placeholder.js**
'// Get the input element by its name attribute
const inputElement = document.querySelector('input[name="acf[field_629501a9d128c][number]"]');

// Set the new placeholder value
inputElement.placeholder = "+31 12 1234567";'

**Comment by Log1x** [comment]
Added in v1.2.5

**Comment by chriscapisce** [comment]
Thanks a lot for your quick respons and action. Is it possible for the placeholder (and output on the frontend) to respect the exact spacing within the number?

For example:

Landline phone number:
+31 229 56 78 90
+31 20 623 45 67
Mobile phone number:
+31 6 54 32 23 45

Thanks again!

**Comment by Log1x** [comment]
No problem. Not 100% sure what you mean. The placeholder its self should respect any spacing (even a non-phone number string).

As far as the phone number its self, is [libphonenumber](https://github.com/giggsey/libphonenumber-for-php) not properly formatting it?

**Comment by chriscapisce** [comment]
I mean that if I put this in the placeholder: +31 6 12 34 56 78 it will get correctly displayed as the placeholder in the backend but as soon as I enter the phone number it get formatted automatically like this: +31 6 12345678. 
It than displays in the frontend like so: +31612345678.

**Comment by Log1x** [comment]
Can you share the full output of `$yourNumber->toArray()`?

Perhaps investigate if there's something missing that would make it properly format as intended in https://github.com/giggsey/libphonenumber-for-php

Does it format as intended with https://giggsey.com/libphonenumber/ ?

**Comment by chriscapisce** [comment]
Thanks for your help. I did enable `composer require giggsey/libphonenumber-for-php`. 
When I take a look at the giggsey it says that my format should be a [valid result](https://giggsey.com/libphonenumber/?phonenumber=%2B31+6+12+34+56+78+&country=NL&language=nl&region=NL).

Here's the array:

```
array(
   	'key' => 'field_629501a9d128d',
   	'label' => 'Mobiel telefoonnummer',
	'name' => 'leden_mobiel_telefoonnummer',
	'aria-label' => '',
	'type' => 'phone_number',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '50',
		'class' => '',
		'id' => '',
	),
	'default_country' => 'nl',
	'placeholder' => '+31 6 12 34 56 78',
	'country' => 'us',
),			
```
Anything else I can do?
