### ISSUE TITLE
get_fields() returns an empty field value

### ISSUE THREAD

**Issue by mikejimlarry** [Log1x/acf-phone-number#77]
I am trying to get all ACF fields for a post and my `phone_number` field was coming up empty.

Tracked it down to the `format_value()` function returning an instance of the PhoneNumber class rather than the value of the field.

I fixed it by changing [line 149 in file src/PhoneNumberField.php](https://github.com/Log1x/acf-phone-number/blob/8f3db32fc11be6168bb30e9070a721c0d68d3149/src/PhoneNumberField.php#L149) to

```php
return (new PhoneNumber($value))->toArray();
```

**Comment by Log1x** [comment]
Does adding `->toArray()` to your `get_field()` value not work?

**Comment by mikejimlarry** [comment]
Hot damn, that does work! It looked like by the time `get_field()` or `get_fields()` was getting the field value it was empty.

**Comment by TimAtTeamlemke** [comment]
It would be helpful to mention the "toArray" method in the readme. I was wondering all the time how to get my data from this strange object :)
