### ISSUE TITLE
Install without Composer

### ISSUE THREAD

**Issue by JacobDB** [Log1x/acf-phone-number#8]
I'm not used to installing WordPress plugins via Composer, so I'm sure this is obvious, but how do I get the field type to show up when building out an ACF form via the back-end? The plugin is activated, but I don't see anything like "Phone Number" when selecting a field type. I see in your README a section titled "ACF Composer" that shows how to add an individual field programmatically (in a way that I'm also unfamiliar with, it doesn't look like ACF's normal way of registering fields), but that doesn't seem to have anything to do with getting the field type to show up in the selector.

**Comment by Log1x** [comment]
I'll push support for installing without Composer tonight.

**Comment by JacobDB** [comment]
Oh, great, thanks much!

**Comment by Log1x** [comment]
#9

**Comment by JacobDB** [comment]
Awesome, it seems to be working, thanks again! Now having an issue with multiple numbers on one page, but I'll open a separate issue for that...

**Comment by Log1x** [comment]
You might need to cast them with `->toArray()` so they aren't all returning the PhoneNumber instance.
