### ISSUE TITLE
Fatal error: Uncaught Error: Class "Log1x\AcfPhoneNumber\PhoneNumberField"

### ISSUE THREAD

**Issue by webmasterpf** [Log1x/acf-phone-number#81]
Hello,

I get this error when I try to activate the plugin.
`Fatal error: Uncaught Error: Class "Log1x\AcfPhoneNumber\PhoneNumberField" not found in /home/xx/www/pfdev/wordpress/wp-content/plugins/acf-phone-number/plugin.php:52 Stack trace: #0 /home/xx/www/pfdev/wordpress/wp-content/plugins/acf-phone-number/plugin.php(38): class@anonymous->register() #1 /home/xx/www/pfdev/wordpress/wp-includes/class-wp-hook.php(310): class@anonymous->__invoke('') #2 /home/xx/www/pfdev/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array) #3 /home/xx/www/pfdev/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 /home/xx/www/pfdev/wordpress/wp-settings.php(610): do_action('after_setup_the...') #5 /home/xx/www/pfdev/wordpress/wp-config.php(102): require_once('/home/xx...') #6 /home/xx/www/pfdev/wordpress/wp-load.php(50): require_once('/home/xx...') #7 /home/xx/www/pfdev/wordpress/wp-blog-header.php(13): require_once('/home/xx...') #8 /home/xx/www/pfdev/wordpress/index.php(17): require('/home/xx...') #9 {main} thrown in /home/xx/www/pfdev/wordpress/wp-content/plugins/acf-phone-number/plugin.php on line 52`

Are you aware of it ? How can I get my website back ?

Thanks

**Comment by Log1x** [comment]
Make sure you download the release zip, not the source code.

https://github.com/Log1x/acf-phone-number/releases/download/v1.2.5/acf-phone-number-v1.2.5.zip

**Comment by webmasterpf** [comment]
So can I do:  `composer require log1x/acf-phone-number:1.2.5` ?

**Comment by Log1x** [comment]
Yeah Composer is fine too.

**Comment by webmasterpf** [comment]
Bad news. I still get the right version.
```
 - Installing giggsey/locale (2.4): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.28.0): Extracting archive
  - Installing giggsey/libphonenumber-for-php (8.13.23): Extracting archive
  - Installing log1x/acf-phone-number (v1.2.5): Extracting archive
```
and path is the right one: 
```
 ls -la ~/www/pfdev/wordpress/wp-content/plugins/
drwxrwxr-x  5 acf-phone-number
```
So what can I do more to get back the plugin page and the entire website ?

**Comment by Log1x** [comment]
> So what can I do more to get back the plugin page and the entire website ?
Just rename the plugin folder or uninstall it with Composer.

**Comment by webmasterpf** [comment]
ok I get the zip file, 
~/www/pfdev/wordpress$ curl -O https://github.com/Log1x/acf-phone-number/releases/download/v1.2.5/acf-phone-number-v1.2.5.zip

But I can't unzip it:
```
Archive:  wp-content/plugins/acf-phone-number-v1.2.5.zip
  End-of-central-directory signature not found.  Either this file is not   a zipfile, or it constitutes one disk of a multi-part archive.  In the   latter case the central directory and zipfile comment will be found on   the last disk(s) of this archive.
```
I will investigate and will keep you in touch.

**Comment by Log1x** [comment]
I think that's because the GitHub URL 301's or something and you would need more arguments for `curl` – can you just use `wget`?

**Comment by webmasterpf** [comment]
You're right, wget is better and allow to unzip the folder. Then I can activate the plugin via the UI. Thanks
