### ISSUE TITLE
Uncaught Error: Class "Log1x\AcfPhoneNumber\PhoneNumberField" not found

### ISSUE THREAD

**Issue by omniacode** [Log1x/acf-phone-number#82]
Receiving the following error message upon installation:

An error of type E_ERROR was caused in line 52 of the file /home/apppath/public_html/wp-content/plugins/acf-phone-number-master/plugin.php](https://github.com/Log1x/acf-phone-number/issues/apppath/public_html/wp-content/plugins/acf-phone-number-master/plugin.php). 

Error message: Uncaught Error: Class "Log1x\AcfPhoneNumber\PhoneNumberField" not found in /home/[apppath/public_html/wp-content/plugins/acf-phone-number-master/plugin.php:52](https://github.com/Log1x/acf-phone-number/issues/apppath/public_html/wp-content/plugins/acf-phone-number-master/plugin.php:52)

**Comment by Log1x** [comment]
How are you installing the plugin? Did you use the release zip or the source code zip?

**Comment by omniacode** [comment]
I believe the source code zip, where do I find the release zip?

**Comment by Log1x** [comment]
https://github.com/Log1x/acf-phone-number/releases

It'll be the acf-phone-number-v1.2.5.zip link for the current release

**Comment by omniacode** [comment]
Thanks for the quick responses, greatly appreciated. Github has changed quite a bit since I've last been here.
