### ISSUE TITLE
There has been a critical error in the plugin when installing

### ISSUE THREAD

**Issue by mhasanmeet** [Log1x/acf-phone-number#84]
The message show in the website when installing the plugin "There has been a critical error on this website."

![Screenshot_4](https://github.com/Log1x/acf-phone-number/assets/24842666/6305bffa-bc6a-4a13-8512-9a0a58aa672f)

Here is the debug log. For security purpose I change my domain name

`[23-Dec-2023 17:47:20 UTC] PHP Fatal error:  Uncaught Error: Class "Log1x\AcfPhoneNumber\PhoneNumberField" not found in /home/u496007041/domains/domain.com/public_html/cb/wp-content/plugins/acf-phone-number-master/plugin.php:52
Stack trace:
#0 /home/u496007041/domains/domain.com/public_html/cb/wp-content/plugins/acf-phone-number-master/plugin.php(38): class@anonymous->register()
#1 /home/u496007041/domains/domain.com/public_html/cb/wp-includes/class-wp-hook.php(324): class@anonymous->__invoke()
#2 /home/u496007041/domains/domaincom/public_html/cb/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /home/u496007041/domains/domain.com/public_html/cb/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/u496007041/domains/domain.com/public_html/cb/wp-settings.php(621): do_action()
#5 /home/u496007041/domains/domain.com/public_html/cb/wp-config.php(105): require_once('/home/u49600704...')
#6 /home/u496007041/domains/domain.com/public_html/cb/wp-load.php(50): require_once('/home/u49600704...')
#7 /home/u496007041/domains/domain.com/public_html/cb/wp-blog-header.php(13): require_once('/home/u49600704...')
#8 /home/u496007041/domains/domain.com/public_html/cb/index.php(17): require('/home/u49600704...')
#9 {main}
  thrown in /home/u496007041/domains/domain.com/public_html/cb/wp-content/plugins/acf-phone-number-master/plugin.php on line 52
[23-Dec-2023 17:47:24 UTC] PHP Fatal error:  Uncaught Error: Class "Log1x\AcfPhoneNumber\PhoneNumberField" not found in /home/u496007041/domains/domain.com/public_html/cb/wp-content/plugins/acf-phone-number-master/plugin.php:52
Stack trace:
#0 /home/u496007041/domains/domain.com/public_html/cb/wp-content/plugins/acf-phone-number-master/plugin.php(38): class@anonymous->register()
#1 /home/u496007041/domains/domain.com/public_html/cb/wp-includes/class-wp-hook.php(324): class@anonymous->__invoke()
#2 /home/u496007041/domains/domain.com/public_html/cb/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /home/u496007041/domains/domain.com/public_html/cb/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/u496007041/domains/domain.com/public_html/cb/wp-settings.php(621): do_action()
#5 /home/u496007041/domains/domain.com/public_html/cb/wp-config.php(105): require_once('/home/u49600704...')
#6 /home/u496007041/domains/domain.com/public_html/cb/wp-load.php(50): require_once('/home/u49600704...')
#7 /home/u496007041/domains/domain.com/public_html/cb/wp-blog-header.php(13): require_once('/home/u49600704...')
#8 /home/u496007041/domains/domain.com/public_html/cb/index.php(17): require('/home/u49600704...')
#9 {main}
  thrown in /home/u496007041/domains/domain.com/public_html/cb/wp-content/plugins/acf-phone-number-master/plugin.php on line 52`

**Comment by mhasanmeet** [comment]
![Uploading Screenshot_32.png…]()

**Comment by mhasanmeet** [comment]
![Screenshot_32](https://github.com/Log1x/acf-phone-number/assets/24842666/48f329ea-95fd-47ef-99ba-34627f43ffe8)

**Comment by Log1x** [comment]
Download the release of the plugin, not the source code.

https://github.com/Log1x/acf-phone-number/releases/tag/v1.2.5

**Comment by mhasanmeet** [comment]
Thanks, Brandon, I did not notice you mentioned the released zip. Thanks again for your amazing work!
