### ISSUE TITLE
Fatal error when activating (PHP 8.2.x)

### ISSUE THREAD

**Issue by filip-van-hoeckel** [Log1x/acf-phone-number#89]
Fatal error: Uncaught Error: Class "Log1x\AcfPhoneNumber\PhoneNumberField" not found in \<webroot>\wp-content\plugins\acf-phone-number\plugin.php:48

Please advise, thanks.

**Comment by Log1x** [comment]
Download the actual release, not the source code. https://github.com/Log1x/acf-phone-number/releases
