### ISSUE TITLE
v1.3.0 returning a Parse Error upon install

### ISSUE THREAD

**Issue by jordachelouis** [Log1x/acf-phone-number#90]
Upon installing v1.3.0, wordpress returns the attached parse error.  v1.2.6 install is installed and activated okay.

![github_acf-phone-number_error_v1 3 0](https://github.com/user-attachments/assets/001a2815-7f11-49a3-b72d-995b64caf121)

**Comment by Log1x** [comment]
sorry about that, I wasn't thinking and used `match` forgetting php 7.x support. just pushed a release with this fixed.
